FROM python:3.10-slim

WORKDIR /app

ADD . /app
 
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
 
# CMD ["python", "./01_installs_mart.py", \
#      "python", "./02_costs_mart.py", \
#      "python", "./03_orders_mart.py", \
#      "python", "./04_events_mart.py"]