FROM python:3.10-slim
WORKDIR /app

# Add the current directory contents into the container at /app
ADD . /app
# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
# Make port 80 available to the world outside this container
EXPOSE 80
# Run the command to start your application
CMD ["python", "./01_installs_mart.py"] && ["python", "./02_costs_mart.py.py"]\
 && ["python", "./03_orders_mart.py.py"] && ["python", "./04_events_mart.py.py"]